<a href="https://colab.research.google.com/github/NabajeetBarman/AppliedDataProgramming/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

#####################################################################################

This Jupyter Notebook is designed for the CI7340 Applied Data Programming
 Module for the MSc. Data Science degree programm at Kingston University.

Parts of this module is borrowed from the official [Numpy Manual v1.21](https://numpy.org/doc/stable/#)

A Reference Book for further learning - if interested, [*Guide to Numpy by Travis E. Oliphant*](https://archive.org/details/NumPyBook/mode/2up)

Copyright@ *Nabajeet Barman*, Kingston University, London, UK

#####################################################################################

## Topics Covered:

* Introduction to Numpy
* Installing NumPy
* Initializing a NumPy array
* NumPy Operations
* Basic Array Operations






## About Numpy
Numpy is short for Numerical Python. 

NumPy is an Open Source Python Library which is used universally across all fields of science and engineering and is the fundamental package needed for scientific computing with Python. 

The NumPy package contains:
*   A powerful N-dimensional array object (*ndarray*)
*   Basic linear algebra functions
*   Sophisticated (broadcasting) functions
*   Basic Fourier transforms
*   Sophisticated random number capabilities
*   Tools for integrating Fortran code
*   Tools for integrating C/C++ code


Interesting paper: https://www.nature.com/articles/s41586-020-2649-2


![Anatomy of a Figure ](https://drive.google.com/uc?export=view&id=1v7AS-0xTof66bhaqaGaTMgGZJg6x9HaF)

# Installing NumPy

If you already have Python, you can install NumPy with:



In [ ]:
!pip install numpy

For installation with conda, one can use `conda install numpy`

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it which can be done using the following statement:

In [ ]:
import numpy as np 
# We have here shortened numpy as np in order to save time. 
# This is a convention followed at many places, 
# and hence readable and udnerstandable to anyone.

You can add multi line comments here using `Ctrl + /` or using the triple single quotes as shown below. It will be ignored as a doc string within the function.
```
'''
We have here shortened numpy as np in order to save time. 
This is a convention followed at many places, 
and hence readable and understandable to anyone.
'''
```



### What is a NumPy N-Dimensional Array (ndarray)?

>* It is an efficient multidimensional array providing fast array-oriented arithmetic operations.
>* An ndarray as any other array, it is a container for homogeneous data (Elements of the same type)
>* In NumPy, data in an ndarray is simply referred to as an array.
>* As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing operations.
>* For numerical data, NumPy arrays are more efficient for storing and manipulating data than the other built-in Python data structures.

### Advantages of NumPy arrays:
> * Faster
> * More compact
> * Consumes less memory
> * Convenient to use
> * Provides a mechanism of specifying the data types
> * Allows the code to be optimized even further

### Python list vs NumPy array

Datatype: 

>* Python list - different data types withing a single list
>* NumPy array - All elements should be homogeneous

Vectorized Operations

>* The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.
>* NumPy operations perform complex computations on entire arrays without the need for Python for loops.
>* In other words, if you apply a function to an array, it is performed on every item in the array, rather than on the whole array object.
>* In a python list, you will have to perform a loop over the elements of the list.

Memory

>* NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects.
>* NumPy arrays takes significantly less amount of memory as compared to python lists.

For more details on Why Python is slow and how NumPy helps overcomes such shortcomings, visit [this](https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/) blog post by Jake VanderPlas.

### Introduction to Arrays

An array is a central data structure of the NumPy library. It is a grid of values and contains information about the raw data, how to locate an element, and how to interpret an element. The elements are all of the same type, referred to as the array `dtype`. 

> In NumPy, dimensions are called axes.

> Array Shape: The shape of the array is a tuple of non-integers that specify the sizes of each dimension.

> Indexing: An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. 

> Rank of the array = number of dimensions. 

### Definition: `ndarray`, `vector`, `matrix` and `Tensor`

* ndarray is short for N-dimensional array and is used to represent both Matrices and Vectors

* A vector is an array with a single dimension (there’s no difference between row and column vectors), 

* A matrix refers to an array with two dimensions. 

* Tensor for 3-D or higher dimensional arrays.

# Initializing a NumPy array

NumPy arrays can be initialized from Python Lists using the `np.array()` function as:

In [ ]:
vec_a = np.array([1, 2, 3, 4, 5, 6])

Remember you can just add a question mark before the command to get help!!!

In [ ]:
?np.array

In [ ]:
vec_a #shows the data type along with contents

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(vec_a)  # print the array

[1 2 3 4 5 6]


In [ ]:
# initializing a 3x3 array
arr = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

Use the above command to define a Matrix (np.matrix is not recommended)

In [ ]:
arr # shows the data type along with contents

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
print(arr) # print the array

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


###Accessing elements in the array

Array elements can be accessed using square brackets.
> *Reminder*: Indexing in Python starts from 0.

In [ ]:
print(arr[0, 0])

1


In [ ]:
arr[1, 1]

6

### Checking the dimensions of the array

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

In [ ]:
arr.ndim

2

### Checking the shape of the array

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
# shape of the array
arr.shape

(3, 3)

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

In [ ]:
# number of elements in an array
arr.size

9

### NumPy Standard Data Types

Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array. This means it gives us information about: 

*   Type of the data (integer, float, Python object, etc.)
*   Size of the data (number of bytes)
*   The byte order of the data (little-endian or big-endian)
* * Read more here: https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html
*   If the data type is a sub-array, what is its shape and data type?

![Anatomy of a Figure ](https://drive.google.com/uc?export=view&id=1OZN4g1ybA7GX_cBUemDBiepZXHPrmzDy)

### Finding the datatype of the created array

In [ ]:
arr.dtype

dtype('int64')

### Specifying the data type (`dtype`)

* The default data type is `np.float64`.
* Specific datatype can be mentioned using the `dtype` keyword

In [ ]:
np.ones(3, dtype=np.int64)

array([1, 1, 1])

Compare it with the default one

In [ ]:
np.ones(3)

array([1., 1., 1.])

# -------------------------------------------------------------

### Qn: Why previously vec_a was dtype int64 and not the default float64?

In [ ]:
vec_a = np.array([1, 2, 3, 4, 5, 6])
vec_a.dtype

dtype('int64')

In [ ]:
vec_a = np.array([1, 2.0, 3, 4, 5, 6])
vec_a.dtype

dtype('float64')

In [ ]:
vec_a = np.array([])
vec_a.dtype

dtype('float64')

Changing `dtype` after array creation

In [ ]:
int_array = np.array([1, 2, 3, 4, 5])
print("Initial dtype is", int_array.dtype)
float_array = int_array.astype(np.float64)
print("After dtype change",float_array.dtype)

Initial dtype is int64
After dtype change float64


Check the arrays for difference

In [ ]:
int_array

array([1, 2, 3, 4, 5])

In [ ]:
float_array

array([1., 2., 3., 4., 5.])

Check below for the difference

In [ ]:
int_array = np.array([1.5, 2, 3.6, 4, 5])
print("Initial dtype is", int_array.dtype)
float_array = int_array.astype(np.float64)
print("After dtype change",float_array.dtype)

Initial dtype is float64
After dtype change float64


Check the arrays for difference

In [ ]:
int_array

array([1.5, 2. , 3.6, 4. , 5. ])

In [ ]:
float_array

array([1.5, 2. , 3.6, 4. , 5. ])

How to correctly define:

In [ ]:
int_array = np.array([1.5, 2, 3.6, 4, 5], dtype=np.int64)
print("Initial dtype is", int_array.dtype)
float_array = int_array.astype(np.float64)
print("After dtype change",float_array.dtype)

Initial dtype is int64
After dtype change float64


Check the arrays for difference

In [ ]:
int_array

array([1, 2, 3, 4, 5])

In [ ]:
float_array

array([1., 2., 3., 4., 5.])

## Initializing different types of numpy arrays

In the following section, we will discuss the following:

> * `np.zeros()`
> * `np.ones()`
> * `np.empty()`
> * `np.arange()`
> * `np.linspace()`

and some other interesting methods to create numpy arrays

**Recall Maths and Stats Lecture...**

(Recap) To create a numpy array, we can se the function `np.array` as below:

In [ ]:
 np.array([1, 2, 3])

array([1, 2, 3])

Creating a zero array ( an array filled with 0s)

In [ ]:
np.zeros(3) #defaults to dtype float64

array([0., 0., 0.])

Creating a all zeros matrix of dimension 3x4:

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Similarly, creating a ones array (an array filled with 1s)

In [ ]:
np.ones(3)

array([1., 1., 1.])

Creating a all ones matrix of dimension 3x4:

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 3d all ones matrix
mat_3d = np.ones((4,3,3))
print(mat_3d)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Note: By default the dtype is `float64`

In [ ]:
mat_3d.dtype

dtype('float64')

In [ ]:
# to initialize a matrix with dtype int32
mat_3dint = np.ones((4,3,3),dtype='int32')#
print(mat_3dint)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Creating an empty array using `np.empty()` created an array filled with random values (which depends on the state of the memory).

Note: `np.empty()` is preferred over `np.zeros()` or `np.ones()` or something similar is when there is need for speed. `np.zeros()` and `np.ones()` are widely used in the field of Machine Learning or Data Science to initialize NumPy arrays.

In [ ]:
np.empty(7) # creating an empty array with 7 elements

array([4.63910596e-310, 2.01589600e-312, 2.12199579e-312, 2.12199579e-312,
       2.56761491e-312, 2.14321575e-312, 8.70018274e-313])

Note: Please note that ideally the values should be garbage but does not appear to be in some cases. Higher numbers should ideally work fine.

See: https://stackoverflow.com/questions/54725478/are-the-values-returned-by-numpy-empty-random-or-not


Instead of creating an empty array, you can also create an array with any value you want

In [ ]:
np.full((3,3), 57.6)

array([[57.6, 57.6, 57.6],
       [57.6, 57.6, 57.6],
       [57.6, 57.6, 57.6]])

In [ ]:
np.full((3,3), 57.6, dtype='int64')

array([[57, 57, 57],
       [57, 57, 57],
       [57, 57, 57]])

In [ ]:
mat_3dint = np.ones((4,3,3),dtype='int32')#
np.full_like(mat_3dint, 12)

array([[[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]], dtype=int32)

**Creating an array with a range of elements**



In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

 Creating an array that contains a range of evenly spaced intervals




In [ ]:
np.arange(1, 10, 2) # Syntax is first number, last number, and the step size.

array([1, 3, 5, 7, 9])

Creating an array with values that are spaced linearly in a specified interval using `np.linspace()`

In [ ]:
np.linspace(1, 15, num=5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

Creating a bigger array by repeating an array

In [ ]:
arr = np.array([1,2,3])
print(arr)
rep_arr = np.repeat(arr,4,axis=0)
print("\n",rep_arr)

[1 2 3]

 [1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
# if you want it to repate as rows
arr = np.array([[1,2,3]])  # notice the double brackets
print(arr)
rep_arr = np.repeat(arr,4,axis=0)
print("\n",rep_arr)

[[1 2 3]]

 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


#NumPy Operations
##Indexing and slicing

In [ ]:
sample_array = np.arange(5,15)
print(sample_array)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
# accessing second element of the array
sample_array[1]

6

In [ ]:
# accessing first four elements of the array
sample_array[:4]

array([5, 6, 7, 8])

In [ ]:
# accessing all elements after the fourth element of the array
sample_array[4:]

array([ 9, 10, 11, 12, 13, 14])

Creating an array slice/subset

In [ ]:
# accessing second element of the array
sam_array_slice = sample_array[2:4]
print(sam_array_slice)

[7 8]


Slicing 2D arrays

In [ ]:
sample_2darray = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(sample_2darray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
sample_2darray[:2,2:4]

array([[3, 4],
       [7, 8]])

**Note: The result includes the start index, but excludes the end index.**


## Copying an array

Be careful when copying an array

In [ ]:
arr =  np.array([1,2,3])
print(arr)
arr_copy = arr
print(arr_copy)

[1 2 3]
[1 2 3]


In [ ]:
# If you make any changes to arr_copy
arr_copy[1] = 10
print(arr_copy)

[ 1 10  3]


In [ ]:
#check your original array
print(arr)

[ 1 10  3]


Copying an array using the = sign results a array which points to the original array

To create an array copy, use the following:

In [ ]:
arr =  np.array([1,2,3])
arr_copy = arr.copy()
print(arr_copy)

[1 2 3]


Now check the results again

In [ ]:
arr_copy[1] = 10
print(arr_copy)
print(arr)

[ 1 10  3]
[1 2 3]


## Sorting

In this section, we will discuss:

* `np.sort()` #sorting array in ascending order

Syntax: `numpy.sort(a, axis=-1, kind=None, order=None)`

> where,  
          > * a: array to be sorted
          > * axis (optional): int or None Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.
          > * kind (optional): {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

For more details, refer [here](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort)



In [ ]:
sample_array = np.array([2, 0, 5, 1, 9, 6, 5, 3, 7, 4, 6, 8])

sorting the array `sample_array` in ascending order

In [ ]:
np.sort(sample_array)

array([0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [ ]:
# Another Example
unsort_array = np.random.randn(5, 3)
print("Unsorted array:\n", unsort_array)
sorted_array= np.sort(unsort_array)
print("\nSorted array:\n", sorted_array)
# sorted using np.sort that returns an array instead of 
# unsort_array.sort() that doesnt return an array object

Unsorted array:
 [[-0.10428181 -0.26548622 -0.41979587]
 [ 0.81671607 -0.22236316  0.28442332]
 [-1.33947208 -0.01243863 -0.38793399]
 [ 0.41591426 -0.42166086  0.24926768]
 [-0.38082797  0.92633566 -0.29729638]]

Sorted array:
 [[-0.41979587 -0.26548622 -0.10428181]
 [-0.22236316  0.28442332  0.81671607]
 [-1.33947208 -0.38793399 -0.01243863]
 [-0.42166086  0.24926768  0.41591426]
 [-0.38082797 -0.29729638  0.92633566]]


In [ ]:
unsort_array = np.array([[-0.68890454, -0.72456373, 0.84461118],
 [-0.26276529,  1.57258979, -1.44918071],
 [-1.71499192,  0.41779693,  1.31305583],
 [ 0.08198237, -0.19772458,  0.40867152],
 [-1.21142084,  0.18889558, -2.19407554]])
print("Unsorted array \n", unsort_array)
print("\n")
unsort_array.sort(-1) # sorts along the last axis (row wise)
# ndarray.sort() is inplace, np.sort is not
print("Sorted array \n", unsort_array)

Unsorted array 
 [[-0.68890454 -0.72456373  0.84461118]
 [-0.26276529  1.57258979 -1.44918071]
 [-1.71499192  0.41779693  1.31305583]
 [ 0.08198237 -0.19772458  0.40867152]
 [-1.21142084  0.18889558 -2.19407554]]


Sorted array 
 [[-0.72456373 -0.68890454  0.84461118]
 [-1.44918071 -0.26276529  1.57258979]
 [-1.71499192  0.41779693  1.31305583]
 [-0.19772458  0.08198237  0.40867152]
 [-2.19407554 -1.21142084  0.18889558]]


In [ ]:
unsort_array = np.array([[-0.68890454, -0.72456373, 0.84461118],
 [-0.26276529,  1.57258979, -1.44918071],
 [-1.71499192,  0.41779693,  1.31305583],
 [ 0.08198237, -0.19772458,  0.40867152],
 [-1.21142084,  0.18889558, -2.19407554]])
print("Unsorted array \n", unsort_array)
print("\n")
unsort_array.sort(0) # sort along the first axis (column wise)
print("Sorted array \n", unsort_array)

Unsorted array 
 [[-0.68890454 -0.72456373  0.84461118]
 [-0.26276529  1.57258979 -1.44918071]
 [-1.71499192  0.41779693  1.31305583]
 [ 0.08198237 -0.19772458  0.40867152]
 [-1.21142084  0.18889558 -2.19407554]]


Sorted array 
 [[-1.71499192 -0.72456373 -2.19407554]
 [-1.21142084 -0.19772458 -1.44918071]
 [-0.68890454  0.18889558  0.40867152]
 [-0.26276529  0.41779693  0.84461118]
 [ 0.08198237  1.57258979  1.31305583]]


In [ ]:
unsort_array = np.array([[-0.68890454, -0.72456373, 0.84461118],
 [-0.26276529,  1.57258979, -1.44918071],
 [-1.71499192,  0.41779693,  1.31305583],
 [ 0.08198237, -0.19772458,  0.40867152],
 [-1.21142084,  0.18889558, -2.19407554]])
print("Unsorted array", unsort_array)
unsort_array.sort() # default is -1 
print("Sorted array", unsort_array)

Unsorted array [[-0.68890454 -0.72456373  0.84461118]
 [-0.26276529  1.57258979 -1.44918071]
 [-1.71499192  0.41779693  1.31305583]
 [ 0.08198237 -0.19772458  0.40867152]
 [-1.21142084  0.18889558 -2.19407554]]
Sorted array [[-0.72456373 -0.68890454  0.84461118]
 [-1.44918071 -0.26276529  1.57258979]
 [-1.71499192  0.41779693  1.31305583]
 [-0.19772458  0.08198237  0.40867152]
 [-2.19407554 -1.21142084  0.18889558]]


## Concatenate



In [ ]:
np.concatenate((unsort_array, unsort_array+2),axis=0) #default, stacked by row

array([[-0.72456373, -0.68890454,  0.84461118],
       [-1.44918071, -0.26276529,  1.57258979],
       [-1.71499192,  0.41779693,  1.31305583],
       [-0.19772458,  0.08198237,  0.40867152],
       [-2.19407554, -1.21142084,  0.18889558],
       [ 1.27543627,  1.31109546,  2.84461118],
       [ 0.55081929,  1.73723471,  3.57258979],
       [ 0.28500808,  2.41779693,  3.31305583],
       [ 1.80227542,  2.08198237,  2.40867152],
       [-0.19407554,  0.78857916,  2.18889558]])

In [ ]:
np.concatenate((unsort_array, unsort_array+2),axis=1) # stack by columns

array([[-0.72456373, -0.68890454,  0.84461118,  1.27543627,  1.31109546,
         2.84461118],
       [-1.44918071, -0.26276529,  1.57258979,  0.55081929,  1.73723471,
         3.57258979],
       [-1.71499192,  0.41779693,  1.31305583,  0.28500808,  2.41779693,
         3.31305583],
       [-0.19772458,  0.08198237,  0.40867152,  1.80227542,  2.08198237,
         2.40867152],
       [-2.19407554, -1.21142084,  0.18889558, -0.19407554,  0.78857916,
         2.18889558]])

## Reshaping, Transposing and Flattening Arrays

Here we will discuss:

* `ndarray.reshape()`
* `ndarray.transpose()`
* `ndarray.T()`
* `ndarray.flip()`
* `ndarray.flatten()`
* `ndarray.ravel()`

### Reshaping an array

`ndarray.reshape()` will give a new shape to an array without changing the data.

In [ ]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
reshaped_array = sample_array.reshape(2,5)
print(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# another example
reshaped_array = sample_array.reshape(5,2)
print(reshaped_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
reshaped_array.transpose()

### Transposing an array

`ndarray.transpose()` will transpose an array

In [ ]:
sample_array.shape

(10,)

By default its in row first.

In [ ]:
sample_array.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_array.transpose().shape

(10,)

In [ ]:
sample_col_array = sample_array.reshape(1,-1)

In [ ]:
sample_col_array.shape

(1, 10)

### Reverse (flip) an array

`np.flip()` function allows flipping or reverse the contents of an array along an axis

In [ ]:
sample_array = np.arange(10)
print("Sample array",sample_array)
# flip the sample _array
reversed_array = np.flip(sample_array)
print("Reversed sample array",reversed_array)

Sample array [0 1 2 3 4 5 6 7 8 9]
Reversed sample array [9 8 7 6 5 4 3 2 1 0]


Reverse a 2D Array

In [ ]:
sample_2darray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Sample 2D array \n", sample_2darray)
print("\n")
# flip the sample _array
reversed_2Darray = np.flip(sample_2darray)
print("Reversed sample 2D array \n",reversed_2Darray)

Sample 2D array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reversed sample 2D array 
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Reverse only the rows

In [ ]:
# Reverse only the rows
reversed_2Darray_rows = np.flip(sample_2darray, axis=0)
print("Reversed sample array",reversed_2Darray_rows)

Reversed sample array [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Reverse only the columns

In [ ]:
# Reverse only the columns
reversed_2Darray_rows = np.flip(sample_2darray, axis=1)
print("Reversed sample array",reversed_2Darray_rows)

Reversed sample array [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


Flattening an array

*Note*: When you use flatten, changes to your new array won’t change the parent array.

In [ ]:
sample_2darray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Sample 2D array", sample_2darray)
# flatteing the sample 2d array into a 1D array
flattened_2Darray = sample_2darray.flatten()
print("Reversed sample 2D array",flattened_2Darray)

Sample 2D array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed sample 2D array [ 1  2  3  4  5  6  7  8  9 10 11 12]


Flattening an array using `ndarray.ravel()`

*Note:* When you use ravel, the changes you make to the new array will affect the parent array.

In [ ]:
sample_2darray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Sample 2D array", sample_2darray)
# flatteing the sample 2d array into a 1D array
flattened_2Darray = sample_2darray.ravel()
print("\n Reversed sample 2D array",flattened_2Darray)
# changes to reversed array
flattened_2Darray[1] = 33 # assigning new value
print("\n Original 2D array",sample_2darray)

Sample 2D array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reversed sample 2D array [ 1  2  3  4  5  6  7  8  9 10 11 12]

 Original 2D array [[ 1 33  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Assignments

## DIY Workshop 

Download the [Jupyter Notebook](https://colab.research.google.com/drive/1PR9SfsXOtPeZ9zExkUNWk3nQ0f8j3pTB?usp=sharing) and answer the questions.

